name: network
channels:
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.2.0
  - absl-py=0.15.0
  - astor=0.8.1
  - blas=1.0
  - ca-certificates=2022.6.15
  - certifi=2021.5.30
  - cycler=0.11.0
  - dataclasses=0.8
  - freetype=2.10.4
  - gast=0.5.3
  - grpcio=1.35.0
  - h5py=2.10.0
  - hdf5=1.10.4
  - icu=58.2
  - importlib-metadata=4.8.1
  - jpeg=9e
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.2
  - kiwisolver=1.3.1
  - libpng=1.6.37
  - libprotobuf=3.17.2
  - libtiff=4.2.0
  - lz4-c=1.9.3
  - markdown=3.3.4
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - nibabel=4.0.1
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openssl=1.1.1q
  - packaging=21.3
  - pillow=8.3.1
  - pip=21.2.2
  - plotly=5.6.0
  - protobuf=3.17.2
  - pydicom=2.3.0
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - python=3.6.13
  - python-dateutil=2.8.2
  - qt=5.9.7
  - scipy=1.5.2
  - setuptools=58.0.4
  - sip=4.19.8
  - six=1.16.0
  - sqlite=3.38.5
  - tenacity=8.0.1
  - tensorboard=1.14.0
  - tensorflow=1.14.0
  - tensorflow-base=1.14.0
  - tensorflow-estimator=1.14.0
  - termcolor=1.1.0
  - tk=8.6.12
  - tornado=6.1
  - typing_extensions=4.1.1
  - werkzeug=2.0.3
  - wheel=0.37.1
  - wrapt=1.12.1
  - xz=5.2.5
  - zipp=3.6.0
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - autopep8==1.7.0
    - pycodestyle==2.9.1
    - toml==0.10.2
